# Generated by Django 5.2.3 on 2025-06-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cv_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
