# Generated by Django 5.2.3 on 2025-06-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analyzer', '0003_applicant_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysis',
            name='interview_questions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
