# Generated by Django 5.2.3 on 2025-06-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analyzer', '0004_cvanalysis_interview_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvanalysis',
            old_name='interview_questions',
            new_name='quiz_data',
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cv_analyzer.applicant')),
            ],
        ),
    ]
